services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DB_ENGINE: sqlite
      SQLITE_PATH: /data/db.sqlite3
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin12345
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    volumes:
      - backend_data:/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000/v1"
    depends_on:
      - backend

volumes:
  backend_data:
